=== 91leinaD/VUXFKS_XMLGyak/XMLTaskVUXFKS/DomParseVUXFKS/XMLSchemaVUXFKS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Cinemagic">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="mozik" type="mozik_type"/>
                    <xs:element name="dolgoznak" type="dolgoznak_type"/>
                    <xs:element name="eladok" type="eladok_type"/>
                    <xs:element name="kivalasztottak" type="kivalasztottak_type"/>
                    <xs:element name="jegyek" type="jegyek_type"/>
                    <xs:element name="vasarlasok" type="vasarlasok_type"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        
        <xs:key name="Mozi_PK">
            <xs:selector xpath="mozik/mozi"/>
            <xs:field xpath="@MoziID"/>
        </xs:key>
        <xs:key name="Elado_PK">
            <xs:selector xpath="eladok/elado"/>
            <xs:field xpath="@EladoID"/>
        </xs:key>
        <xs:key name="Jegy_PK">
            <xs:selector xpath="jegyek/jegy"/>
            <xs:field xpath="@JegyID"/>
        </xs:key>
        <xs:key name="Vasarlas_PK">
            <xs:selector xpath="vasarlasok/vasarlas"/>
            <xs:field xpath="@VasarlasID"/>
        </xs:key>
        
        <xs:keyref name="Mozi_FK" refer="Mozi_PK">
            <xs:selector xpath="dolgoznak/dolgozik"/>
            <xs:field xpath="@Mozi_IDREF"/>
        </xs:keyref>
        <xs:keyref name="DElado_FK" refer="Elado_PK">
            <xs:selector xpath="dolgoznak/dolgozik"/>
            <xs:field xpath="@Elado_IDREF"/>
        </xs:keyref>
        <xs:keyref name="KElado_FK" refer="Elado_PK">
            <xs:selector xpath="kivalasztottak/kivalaszt"/>
            <xs:field xpath="@Elado_IDREF"/>
        </xs:keyref>
        <xs:keyref name="VElado_FK" refer="Elado_PK">
            <xs:selector xpath="vasarlasok/vasarlas"/>
            <xs:field xpath="@Elado_IDREF"/>
        </xs:keyref>
        <xs:keyref name="KJegy_FK" refer="Jegy_PK">
            <xs:selector xpath="kivalasztottak/kivalaszt"/>
            <xs:field xpath="@Jegy_IDREF"/>
        </xs:keyref>
        <xs:keyref name="VJegy_FK" refer="Jegy_PK">
            <xs:selector xpath="vasarlasok/vasarlas"/>
            <xs:field xpath="@Jegy_IDREF"/>
        </xs:keyref>
        
    </xs:element>
   
   <xs:complexType name="mozik_type">
        <xs:sequence>
            <xs:element name="mozi" type="mozi_type" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
   <xs:complexType name="dolgoznak_type">
        <xs:sequence>
            <xs:element name="dolgozik" type="dolgozik_type" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="eladok_type">
        <xs:sequence>
            <xs:element name="elado" type="elado_type" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="kivalasztottak_type">
        <xs:sequence>
            <xs:element name="kivalaszt" type="kivalaszt_type" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="jegyek_type">
        <xs:sequence>
            <xs:element name="jegy" type="jegy_type" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="vasarlasok_type">
        <xs:sequence>
            <xs:element name="vasarlas" type="vasarlas_type" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
   
    <xs:complexType name="mozi_type">
        <xs:sequence>
            <xs:element name="mozinev" type="xs:string"/>
            <xs:element name="cim" type="cim_type"/>
        </xs:sequence>
        <xs:attribute name="MoziID" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="dolgozik_type">
        <xs:sequence>
            <xs:element name="elerheto" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="Mozi_IDREF" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="Elado_IDREF" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="elado_type">
        <xs:sequence>
            <xs:element name="fhsznev" type="xs:string"/>
            <xs:element name="jelszo" type="xs:string"/>
            <xs:element name="admin" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="EladoID" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="kivalaszt_type">
        <xs:sequence>
            <xs:element name="lefoglalt" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="Elado_IDREF" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="Jegy_IDREF" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="jegy_type">
        <xs:sequence>
            <xs:element name="vetites" type="xs:string"/>
            <xs:element name="sor" type="xs:integer"/>
            <xs:element name="oszlop" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="JegyID" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="vasarlas_type">
        <xs:sequence>
            <xs:element name="vidopont" type="vasarlasidopontType"/>
        </xs:sequence>
        <xs:attribute name="VasarlasID" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="Jegy_IDREF" type="xs:unsignedByte" use="required"/>
        <xs:attribute name="Elado_IDREF" type="xs:unsignedByte" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="cim_type">
        <xs:sequence>
            <xs:element name="irszam" type="xs:integer"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hazszam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="vasarlasidopontType">
        <xs:restriction base="xs:string">
          <xs:pattern value="[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]/[0-9][0-9]*:[0-9][0-9]"/>
        </xs:restriction>
      </xs:simpleType>
     
</xs:schema>

=== 91leinaD/VUXFKS_XMLGyak/XMLTaskVUXFKS/DomParseVUXFKS/XMLVUXFKS.xml
<?xml version="1.0" encoding="UTF-8"?>

<Cinemagic xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaVUXFKS.xsd">
	<mozik>
		<mozi MoziID="01">
			<mozinev>CinemaMiskolc</mozinev>
			<cim>
				<irszam>3500</irszam>
				<utca>Rákóczi</utca>
				<hazszam>15.</hazszam>
			</cim>
		</mozi>
		<mozi MoziID="02">
			<mozinev>CinemaBudapest</mozinev>
			<cim>
				<irszam>1100</irszam>
				<utca>Fő</utca>
				<hazszam>4.</hazszam>
			</cim>
		</mozi>
		<mozi MoziID="03">
			<mozinev>CinemaSalgótarján</mozinev>
			<cim>
				<irszam>3100</irszam>
				<utca>Kiss</utca>
				<hazszam>88.</hazszam>
			</cim>
		</mozi>
	</mozik>
	<dolgoznak>
		<dolgozik Mozi_IDREF="01" Elado_IDREF="01" >
			<elerheto>0</elerheto>
		</dolgozik>
		<dolgozik Mozi_IDREF="02" Elado_IDREF="02">
			<elerheto>1</elerheto>
		</dolgozik>
		<dolgozik Mozi_IDREF="03" Elado_IDREF="03">
			<elerheto>1</elerheto>
		</dolgozik>
	</dolgoznak>
	<eladok>
		<elado EladoID="01" >
			<fhsznev>Béla05</fhsznev>
			<jelszo>ujjelszo1</jelszo>
			<admin>0</admin>
		</elado>
		<elado EladoID="02" >
			<fhsznev>Anna01</fhsznev>
			<jelszo>ujjelszo2</jelszo>
			<admin>0</admin>
		</elado>
		<elado EladoID="03" >
			<fhsznev>Judit08</fhsznev>
			<jelszo>ujjelszo3</jelszo>
			<admin>0</admin>
		</elado>
		<elado EladoID="04" >
			<fhsznev>Péter04</fhsznev>
			<jelszo>ujjelszo4</jelszo>
			<admin>1</admin>
		</elado>
	</eladok>
	<kivalasztottak>
		<kivalaszt Elado_IDREF="03" Jegy_IDREF="01">
			<lefoglalt>0</lefoglalt>
		</kivalaszt>
		<kivalaszt Elado_IDREF="02" Jegy_IDREF="02">
			<lefoglalt>0</lefoglalt>
		</kivalaszt>
		<kivalaszt Elado_IDREF="03" Jegy_IDREF="04">
			<lefoglalt>1</lefoglalt>
		</kivalaszt>
		<kivalaszt Elado_IDREF="02" Jegy_IDREF="06">
			<lefoglalt>1</lefoglalt>
		</kivalaszt>
	</kivalasztottak>
	<jegyek>
		<jegy JegyID="01">
			<vetites>01</vetites>
			<sor>10</sor>
			<oszlop>1</oszlop>
		</jegy>
		<jegy JegyID="02">
			<vetites>01</vetites>
			<sor>10</sor>
			<oszlop>2</oszlop>
		</jegy>
		<jegy JegyID="03">
			<vetites>01</vetites>
			<sor>5</sor>
			<oszlop>4</oszlop>
		</jegy>
		<jegy JegyID="04">
			<vetites>01</vetites>
			<sor>5</sor>
			<oszlop>5</oszlop>
		</jegy>
		<jegy JegyID="05">
			<vetites>02</vetites>
			<sor>11</sor>
			<oszlop>7</oszlop>
		</jegy>
		<jegy JegyID="06">
			<vetites>02</vetites>
			<sor>8</sor>
			<oszlop>9</oszlop>
		</jegy>
	</jegyek>
	<vasarlasok>
		<vasarlas VasarlasID="01" Jegy_IDREF="05" Elado_IDREF="02">
			<vidopont>2021.12.01/10:00</vidopont>
		</vasarlas>
		<vasarlas VasarlasID="02" Jegy_IDREF="03" Elado_IDREF="03">
			<vidopont>2021.12.01/10:08</vidopont>
		</vasarlas>
	</vasarlasok>
</Cinemagic>
